### ISSUE TITLE
Uncaught ReferenceError: rlite is not defined

### ISSUE THREAD

**Issue by gururajmbhandarkar** [chrisdavies/rlite#26]
I'm getting undefined error. What is going wrong ? Please help.

**Comment by chrisdavies** [comment]
You either need to import rlite, if you're using e.g. Webpack:

`import Rlite from 'rlite';`

Or, you need to include rlite.js or rlite.min.js on your page before your
script.

**Comment by gururajmbhandarkar** [comment]
i'm using rlite.min.js and i'm importing it before my main js file. Should i put it inside document.ready function ?

**Comment by chrisdavies** [comment]
I'd have to see your source to be sure, but here is an example of how to include it:

http://jsbin.com/kogalosexe/edit?html,js,console

**Comment by hanoncs** [comment]
Hi @chrisdavies your link is showing that rlite is not defined. I am also having this issue. I have rlite.js in my head and my routes before closing the body and still rlite=undefined.

**Comment by chrisdavies** [comment]
Hm. That is due to jsBin and/or the CDN having issues loading the script. I updated the bin to inline the Rlite min script to eliminate the possibility that Rlite fails to load due to a DNS/CDN issue. If you are seeing this issue, it likely means that the Rlite script itself has failed to load, and you need to diagnose why.  (It's either a DNS issue or the CDN is timing out or something.)

**Comment by Mr-Ruben** [comment]
I was having the same issue... The problem comes from the documentation, which I trusted deeply.

Documentation has this example.

```
<script type="text/javascript">
const route = rlite(notFound, {
  // Default route
  '': function () {
    return 'Home';
  }, ......

```

But if you use it like this inside your html body

```
<script src="rlite.min.js"></script>

<script type="text/javascript">
const route = rlite(notFound, {
  // Default route
  '': function () {
    return 'Home';
  },
...
```
This (if you have downloaded the file)
`<script src="rlite.min.js"></script>`
can be replaced for 
`<script src="https://raw.githubusercontent.com/chrisdavies/rlite/master/rlite.min.js"></script>`

I get a

```
Uncaught ReferenceError: rlite is not defined
    at doc.html:20
```

The solution is as simple as changing  rlite for **Rlite** in the call inside your html.

```
<script type="text/javascript">
const route = Rlite(notFound, {
  // Default route
  '': function () {
    return 'Home';
  },
...
```

Now it works!

Thank you for rlite by the way.
