### ISSUE TITLE
Not a flexible language for setting a template

### ISSUE THREAD

**Issue by jt3k** [chrisdavies/rlite#27]
for example 
not suported urls `/aaa/bbb-:ccc`

**Comment by chrisdavies** [comment]
Right this is by design.

I would write a route like this:

```js
/aaa/bbb/:ccc
```

But if I really need to handle cases like that, I do something like this:

```js
/aaa/:foo
```

And then, I parse it like so:

```js
function myAaaRoute(params) {
   const ccc = params.foo.slice(4);
   // do stuff with ccc
}
```

And so forth.

The reason for the limitation is that it makes parsing of routes less complex, helping to keep the library tight. Also, it means parsing is faster which positively impacts app startup time.

**Comment by jromero** [comment]
I was also bitten by this. It would be nice if it was on the README at least for a heads up.

**Comment by chrisdavies** [comment]
I've added wildcard support since this issue first came up. But I will add a note to the readme.
