### ISSUE TITLE
support history api?

### ISSUE THREAD

**Issue by pwFoo** [chrisdavies/rlite#34]
I sounds like rlite doesn't support history api (browser address bar changes)?
Is there a example / extension how to do browser address bar / history handling?

**Comment by chrisdavies** [comment]
It does. Or, more accurately, it doesn't have anything to do with the browser address bar changes at all (either hash or history or whatever). The rlite consumer is responsible for handling events (either hash change or history) and feeding the appropriate URL into rlite.

**Comment by pjfsilva** [comment]
@chrisdavies while I understand the separation I would strongly advise we improve README to include a pratical example on how to use rlite in a browser scenario with pushstate integration so that it has the same full fledged behaviour of Backbone router or Director.js. 

I believe user adoption will increase with those examples since rlite has some major advantages of performance + less size compared to other 'full' routers.

**Comment by pwFoo** [comment]
At the moment I use https://github.com/krasimir/navigo because of just  works and the examples are fine.

Would move If I get it working with rlite
